TaskSphere/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('authentication/', include(('authentication.urls', 'authentication'), namespace='authentication')),
    path('home/', include(('home.urls', 'home'), namespace='home')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/urls.py
from django.urls import path
from authentication import views

urlpatterns = [
    path('', views.main, name='main'),
    path('signin/', views.SignIn, name='signin'),
    path('signup/', views.SignUp, name='signup'),
    path('choosegroupaction', views.ChooseGroupAction, name='choosegroupaction'),
    path('joingroup/', views.JoinGroup, name='joingroup'),
    path('creategroup/', views.CreateGroup, name='creategroup'),
    path('leavegroup/', views.LeaveGroup, name='leavegroup'),
    path('deleteacc/', views.DeleteAccount, name='deleteaccount'),
    path('signout/', views.SignOut, name='signout'),
]

home/urls.py
from django.urls import path
from home import views

urlpatterns = [
    path('', views.main, name='main'),
    path('employees', views.employees_page, name='employees_page')
]

authentication/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.utils import timezone
from home.models import Group

class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(email, password, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    biography = models.TextField(null=True, blank=True)
    profile_picture = models.ImageField(null=True, blank=True, upload_to="images/")
    firstname = models.CharField(max_length=20, null=True, blank=True)
    lastname = models.CharField(max_length=20, null=True, blank=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField(default=timezone.now)
    group = models.ForeignKey(Group, on_delete=models.SET_NULL, null=True, blank=True, related_name="users")


    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email
    

authentication/forms.py
from typing import Any
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django.core.validators import FileExtensionValidator
from authentication.models import User
from home.models import Group
from django.conf import settings
import os
import json

def getGroupGivenIDEndings():
    endings = {}
    # Load endings from JSON file
    json_file_path = os.path.join(settings.BASE_DIR, 'data', 'group_endings.json')

    if os.path.exists(json_file_path):
        with open(json_file_path, 'r', encoding='utf-8') as file:
            try:
                data = json.load(file)
                for key, value in data.items():
                    endings.update({value: value})
            except json.JSONDecodeError:
                raise ValidationError("Invalid JSON format in group_endings.json")
    return endings

class SignUpForm(UserCreationForm):
    firstname = forms.CharField(
        label="Firstname", 
        max_length=20, 
        required=True, 
        widget=forms.TextInput(attrs={
            'class': 'form-control col-md-6', 
            'placeholder': 'Firstname',
        }),

    )

    lastname = forms.CharField(
        label="Lastname", 
        max_length=20, 
        required=True, 
        widget=forms.TextInput(attrs={
            'class': 'form-control col-md-6',  
            'placeholder': 'Lastname',
        }),
        
    )
    biography = forms.CharField(
        label="Biography",
        max_length=250,
        required=False, 
        widget=forms.Textarea(attrs={
            'class': 'form-control', 
            'placeholder': 'I am using TaskSphere', 
            'rows': '4',
        }),
    )


    def validate_image_file_size(image):
        max_size = 2 * 1024 * 1024  # 2 MB
        if image.size > max_size:
            raise ValidationError("The image may be a maximum of 2MB in size.")
    
    profile_picture = forms.ImageField(
        max_length=30,
        label="Profile picture",
        help_text='<br> <span class="form-text text-white-50">Max size: 2 MB. Allowed formats: .png and .jpg</span>',
        required=False,
        validators=[
            FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']),
            validate_image_file_size
        ],
        widget=forms.ClearableFileInput(attrs={
            'accept': '.jpg, .jpeg, .png',
        })
    )


    class Meta:
        model = User
        fields = ('email', 'password1', 'password2', 'firstname', 'lastname', 'biography', 'profile_picture',)

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)

        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['placeholder'] = 'example@myemail.com'
        self.fields['email'].label = 'Email address'
        self.fields['email'].widget.attrs['required'] = 'required'
        self.fields['email'].help_text = '<span class="form-text text-white-50">Your email is only visible for people in your group.</span>'
        self.fields['email'].max_length = 30,
    

        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['placeholder'] = ''
        self.fields['password1'].label = 'Password'
        self.fields['password1'].help_text = '<ul class="form-text text-white-50"><li>Your password can\'t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can\'t be a commonly used password.</li><li>Your password can\'t be entirely numeric.</li></ul>'


        self.fields['password2'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'
        self.fields['password2'].label = ''
        self.fields['password2'].help_text = '<span class="form-text text-white-50">Enter the same password as before, for verification.</span>'

class CreateGroupForm(forms.ModelForm):
    group_name = forms.CharField(
        label="Groupname", 
        max_length=30, 
        required=True, 
        widget=forms.TextInput(attrs={
            'class': 'form-control', 
            'placeholder': 'For example name of the company',
        }),
    )

    givenID = forms.CharField(
        label="ID", 
        max_length=40, 
        required=True,

        widget=forms.TextInput(attrs={
            'class': 'form-control w-75', 
            'type': 'text',
            'placeholder': 'Example: #45F31qwr4lsc',
        }),
        help_text='<span class="form-text text-white-50">Every group needs an ID. An ID is required so that people can join your group. It is private and only you can see it.</span>'
    )


    givenID_ending = forms.ChoiceField(
        choices=getGroupGivenIDEndings(),
        widget=forms.Select(attrs={
            'class': 'form-select bg-secondary text-white'
        }),
    )


    def clean(self):
        cleaned_data = super().clean()

        givenID = cleaned_data.get('givenID')
        givenID_ending = cleaned_data.get('givenID_ending')

        if givenID and givenID_ending:
            full_givenID = f"{givenID}{givenID_ending}"  

            cleaned_data['givenID'] = full_givenID

        return cleaned_data

    def clean_group_id(self):
        group_id = self.cleaned_data['givenID']
        qs = Group.objects.filter(givenID=group_id)
        if self.instance.pk:
            qs = qs.exclude(pk=self.instance.pk)
        if qs.exists():
            raise forms.ValidationError("This group ID is already taken.")
        return group_id
        

    group_password = forms.CharField(
        label="Group password",
        required=True,
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
        })
    )

    group_biography = forms.CharField(
        label="Group biography",
        max_length=250,
        required=False, 
        widget=forms.Textarea(attrs={
            'class': 'form-control', 
            'placeholder': 'We stick together!', 
            'rows': '4',
        }),
    )

    class Meta:
        model = Group
        exclude = ("id", "created_on")
    

    
	

authentication/views.py
from django.shortcuts import render, redirect, get_object_or_404
from authentication.models import User, Group
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from .forms import SignUpForm, CreateGroupForm, getGroupGivenIDEndings
from django.core.mail import send_mail
from django.conf import settings
from TaskSphere import urls


# Create your views here.

def main(request):
    return render(request, 'authentication/main.html')

def SignIn(request):
    if request.user.is_authenticated:
        messages.error(request, f"You can't sign in because you already are. To do this please sign out.")
        return redirect("authentication:main")
    else:
        if request.method == 'POST':
            email = request.POST['emailInput']
            password = request.POST['passwordInput']

            if len(email) > 30:
                messages.error(request, 'The entered email address is too long.')
                return render(request, 'authentication/signin.html',)

            user = authenticate(request, email=email, password=password)

            if user is None:
                messages.error(request, "Wrong email or password. Please try again.")
                return redirect('authentication:signin')
            else:
                login(request, user)
                if user.group is None:  # in_group is empty
                    return redirect('authentication:main')
                else:
                    return redirect('home:main')
                
    return render(request, 'authentication/signin.html')

def SignUp(request):
    if request.user.is_authenticated:
        messages.error(request, "You can't sign up because you already are. To do this please sign out.")
        return redirect('authentication:main')
    
    signUp_form = SignUpForm(request.POST or None, request.FILES or None)

    if request.method == 'POST' and signUp_form.is_valid():
        # emailAdress = signUp_form.cleaned_data['email']
        # first_name = signUp_form.cleaned_data['firstname']
        # last_name = signUp_form.cleaned_data['lastname']


        signUp_form.save()
        messages.success(request, "Account successfully created.")

        #send_mail(
            #"Thank you for joining TaskSphere",
            #f"Hello, {first_name} {last_name}. \n We are pleased that you have chosen TaskSphere. If any problems arise over time, please contact our support. We wish you a lot of fun and good luck working with Tasksphere!",
            #settings.EMAIL_HOST_USER,
            #[emailAdress],
            #fail_silently=False,
        #)

        return redirect('authentication:signin')
    
    return render(request, 'authentication/signup.html', {'signUp_form': signUp_form,})


def ChooseGroupAction(request):
    if request.user.is_authenticated:
        if request.user.group is not None:
            messages.error(request, "You are already part of a group. Please leave the group first.")
            return redirect('authentication:main')
        else:
            return render(request, 'authentication/chooseGroupAction.html', {'username':request.user.firstname})
    else:
        messages.error(request, "To have access to this page you need to sign in.")
        return redirect('authentication:signin')

def CreateGroup(request):
    if request.user.is_authenticated:
        if request.user.group is not None:
            messages.error(request, "You are already part of a group. Please leave the group first.")
            return redirect('authentication:main')
        else:
            createGroup_form = CreateGroupForm(request.POST or None)
            if request.method == 'POST' and createGroup_form.is_valid():
                givenID = createGroup_form.cleaned_data['givenID']
                createGroup_form.save()
                group = Group.objects.get(givenID=givenID)
                request.user.group = group
                request.user.save()
                messages.success(request, "Group successfully created.")
                return redirect('authentication:main')
            return render(request, 'authentication/createGroup.html', {'createGroup_form': createGroup_form,})
    else:
        messages.error(request, "To have access to this page you need to sign in.")
        return redirect('authentication:signin')

def JoinGroup(request):
    if request.user.is_authenticated:
        if request.user.group is not None:
            messages.error(request, "You already are part of a group. Please leave the group first.")
            return redirect('authentication:main')
        else:
            if request.method == 'POST':
                group_id = request.POST['groupIDInput'] + request.POST['groupIDEndingInput']
                group_password = request.POST['groupPasswordInput']

                group_exists = Group.objects.filter(givenID=group_id).exists()
                
                if not group_exists or not Group.objects.get(givenID=group_id).group_password == group_password:
                    messages.error(request, "You entered the wrong group id or password") 
                    return render(request, 'authentication/joingroup.html', {'groupIDEnding': getGroupGivenIDEndings(), 'selected_value': request.POST['groupIDEndingInput'], 'group_id': request.POST['groupIDInput']})
                else:
                    group = Group.objects.get(givenID=group_id)
                    request.user.group = group
                    request.user.save()
                    messages.success(request, f"You joined the group {group.group_name}.")
                    return redirect('home:main')
                    
            return render(request, 'authentication/joingroup.html', {'groupIDEnding': getGroupGivenIDEndings()})
    else:
        messages.error(request, "To have access to this page you need to sign in.")
        return redirect('authentication:signin')
    
def LeaveGroup(request):
    if request.user.is_authenticated:
        if request.user.group is None:
            messages.error(request, "You are not part of a group.")
            return redirect('authentication:main')
        else:
            user_group = request.user.group.group_name
            request.user.group = None
            request.user.save()
            messages.success(request, f'You left the group "{user_group}" successfully.')

            return redirect('authentication:choosegroupaction')
    else:
        messages.error(request, "To have access to this page you need to sign in.")
        return redirect('authentication:signin')

def DeleteAccount(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            passwordPOST = request.POST['passwordPOST']
            user = authenticate(request, email=request.user.email, password=passwordPOST)

            if user is not None:
                if request.user.group is not None:
                    request.user.group == None
                logout(request)
                User.objects.get(email = user.email).delete()
                # -----------------Send user email to confirm the deletion of the account--------------------------
                messages.success(request, "Deleted your account successfully. We hope to see you again soon!")
                return redirect("authentication:main")
            else:
                messages.error(request, "You have entered the wrong password.")
                return redirect('authentication:deleteaccount')
        return render(request, 'authentication/deleteAccount.html')
    else:
        messages.error(request, "To have access to this page you need to sign in.")
        return redirect('authentication:signin')

def SignOut(request):
    logout(request)
    messages.success(request, 'Successfully logged out.')
    return redirect('authentication:signin')

authentication/templates/authentication/chooseGroupAction.html
{% extends 'authentication/base.html' %}
{% load static %}
{% block title %}Choose an action{% endblock %}
{% block description %}Choose if you want to join an existing group or create one.{% endblock %}
{% block header %}Sign Up{% endblock %}
{% block content %}
<div class="container mt-3 mt-md-5 d-flex justify-content-center appearAnimation">
    <div class="card text-center mb-3 bg-transparent border-1 border-white text-light mt-5" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title fs-5">Hello {{username}}! <br><br> What do you want to do?</h5>
          <a href="{% url 'authentication:joingroup' %}" class="btn btn-secondary border-1 border-white mt-3 fs-5 w-100">Join an existing group</a>
          <a href="{% url 'authentication:creategroup' %}" class="btn btn-secondary border-1 border-white mt-5 fs-5 w-100">Create a new group</a>
        </div>
    </div>
</div>
{% endblock %}

authentication/templates/authentication/createGroup.html
{% extends 'authentication/base.html' %}
{% load static %}
{% block title %}Create a new group{% endblock %}
{% block description %}Create a new group on TaskSphere{% endblock %}
{% block header %}Sign Up{% endblock %}
{% block content %}
<div class="container appearAnimation d-flex justify-content-center fs-6 mt-2 mt-md-4">
    <h4 class="text-white">Create a new group</h4>
</div>
<div class="container text-white mt-3 mt-md-5 mb-4 d-flex justify-content-center appearAnimation">
    <form method="post" action="{% url 'authentication:creategroup' %}">
        {% csrf_token %}
        <div class="form-group">
            {{ createGroup_form.group_name.label_tag|linebreaksbr }}
            {% for error in createGroup_form.group_name.errors %}
            <br><span class="form-text text-warning fs-6">{{ error }}</span>
            {% endfor %}
            {{ createGroup_form.group_name }}
        </div>

        
        <div class="form-group mt-3">
            {{ createGroup_form.givenID.label_tag|linebreaksbr }}
            {% for error in createGroup_form.group_name.errors %}
            <br><span class="form-text text-warning fs-6">{{ error }}</span>
            {% endfor %}
            <div class="input-group">
                {{ createGroup_form.givenID }}
                {{ createGroup_form.givenID_ending }}
            </div>
            {{ createGroup_form.givenID.help_text|safe }}
        </div>

        <div class="form-group mt-3">
            {{ createGroup_form.group_password.label_tag|linebreaksbr }}
            {% for error in createGroup_form.group_password.errors %}
            <br><span class="form-text text-warning fs-6">{{ error }}</span>
            {% endfor %}
            {{ createGroup_form.group_password }}
        </div>

        <div class="form-group mt-3">
            {{ createGroup_form.group_biography.label_tag|linebreaksbr }}
            {% for error in createGroup_form.group_biography.errors %}
            <br><span class="form-text text-warning fs-6">{{ error }}</span>
            {% endfor %}
            {{ createGroup_form.group_biography }}
        </div>
        
        <div class="d-flex justify-content-center mt-5">
            <button type="submit" class="btn btn-lg btn-primary border-1 border-white">Submit</button>
        </div>
    </form>
</div>
{% endblock %}

authentication/templates/authentication/joingroup.html
{% extends 'authentication/base.html' %}
{% load static %}
{% block title %}Join an existing group{% endblock %}
{% block description %}Join an existing group on TaskSphere{% endblock %}
{% block header %}Sign Up{% endblock %}
{% block content %}
<div class="container appearAnimation d-flex justify-content-center fs-6 mt-2 mt-md-4">
    <h4 class="text-white">Join an existing group</h4>
</div>

<div class="container appearAnimation mt-3 mt-md-4">
    <form action="{% url 'authentication:joingroup' %}" method="post" class="text-white">
        {% csrf_token %}
        <div class="mb-3">
            <label for="groupIDInput" class="form-label">Group ID</label>
            <div class="input-group">
                <input value="{{group_id}}" required name="groupIDInput" id="groupIDInput" type="text" class="form-control w-75" aria-describedby="groupIDHelp" aria-label="ID of the group">
                <select required class="form-select bg-secondary text-white" name="groupIDEndingInput" id="groupIDEndingInput">
                    {% if not selected_value%}
                    <option selected value="">?</option>
                    {% endif %}
                    {% for item in groupIDEnding %}
                        {% if item == selected_value %}
                        <option selected value="{{item}}">{{item}}</option>
                        {% else %}
                        <option value="{{item}}">{{item}}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
            <div id="groupIDHelp" class="form-text text-white-50">Replace question mark with the ending of the group ID.</div>
        </div>
        <div class="mb-3">
          <label for="groupPasswordInput" class="form-label">Group Password</label>
          <input required type="password" class="form-control" name="groupPasswordInput" id="groupPasswordInput">
        </div>
        <div class="d-flex justify-content-center mt-5">
            <button type="submit" class="btn btn-lg btn-primary border-1 border-white">Submit</button>
        </div>
    </form>
</div>
{% endblock %}

authentication/templates/authentication/main.html
{% extends 'authentication/base.html' %}
{% load static %}
{% block title %}Authentication{% endblock %}
{% block description %}TaskSphere's main authentication page.{% endblock %}
{% block header %}Authentication{% endblock %}
{% block content %}
<div class="appearAnimation d-flex justify-content-center mt-5 px-3">
    <div class="card text-white bg-transparent mb-3 border-1 border-white mt-sm-5 px-3">
        <div class="card-body d-flex flex-column align-items-center justify-content-center">
            <!--------------------Change template (if user not in group -> he can't leave or change group)----------------->
            {% if user.is_authenticated %}
            <div class="container text-center">
                <div class="row g-4">
                    <div class="col-12">
                        <span class="fs-4">What do you want to do?</span>
                    </div>
                    {% if not user.group == None %}
                    <div class="col-12">
                        <a class="fs-4 mt-3 text-light" href="{% url 'authentication:leavegroup' %}">Change the group</a>
                    </div>
                    {% else %}
                    <div class="col-12">
                        <a class="fs-4 mt-3 text-light" href="{% url 'authentication:choosegroupaction' %}">Join or create a group</a>
                    </div>
                    {% endif %}
                    <div class="col-12">
                        <span class="fs-4 font-monospace">---------------</span>
                    </div>
                    <div class="col-12">
                        <a class="fs-4 mt-3 text-light" href="{% url 'authentication:deleteaccount' %}">Delete your account</a>
                    </div>
                    <div class="col-12">
                        <span class="fs-4 font-monospace">---------------</span>
                    </div>
                    <div class="col-12">
                        <a class="fs-4 mt-3 text-light" href="{% url 'authentication:signout' %}">Sign Out</a>
                    </div>
                </div>
            </div>
            {% else %}
            <span class="fs-4">What do you want to do?</span>
            <a class="fs-4 mt-3 text-light fw-bold" href="{% url 'authentication:signin' %}">Sign In</a>
            <span class="fs-4 mt-3">or</span>
            <a class="fs-4 mt-3 text-light fw-bold" href="{% url 'authentication:signup' %}">Sign Up</a>
            {% endif %}
        </div>
    </div>
</div>

{% if user.is_authenticated and not user.group == None %}
<div class="container appearAnimation d-flex align-items-center justify-content-end mt-5">
    <a class="text-white me-1" href="{% url 'home:main' %}">Return to home page.</a>
    <img src="{% static 'icons/arrow-right.svg' %}" alt="Arrow-right">
</div>
{% endif %}
{% endblock %}

authentication/templates/authentication/signin.html
{% extends 'authentication/base.html' %}
{% load static %}
{% block title %}Sign In{% endblock %}
{% block description %}TaskSphere's sign-in page.{% endblock %}
{% block header %}Sign In{% endblock %}
{% block content %}
<div class="container appearAnimation mt-sm-5 mt-4">
    <form action="{% url 'authentication:signin' %}" method="post" class="text-white">
        {% csrf_token %}
        <div class="mb-3">
          <label for="emailInput" class="form-label">Email address</label>
          <input required  type="email" class="form-control" name="emailInput" id="emailInput" aria-describedby="emailHelp">
          <div id="emailHelp" class="form-text text-white-50">Your email is only visible for people in your group.</div>
        </div>
        <div class="mb-3">
          <label for="passwordInput" class="form-label">Password</label>
          <input required  type="password" class="form-control" name="passwordInput" id="passwordInput">
        </div>
        <div class="d-flex justify-content-center mt-5">
            <button type="submit" class="btn btn-lg btn-primary border-1 border-white">Submit</button>
        </div>
    </form>
</div>

<div class="container appearAnimation d-flex align-items-center justify-content-end mt-5">
    <a class="text-white me-1" href="{% url 'authentication:signup' %}">I don't have an account</a>
    <img src="{% static 'icons/arrow-right.svg' %}" alt="Arrow-right">
</div>
{% endblock %}

authentication/templates/authentication/signup.html
{% extends 'authentication/base.html' %}
{% load static %}
{% block title %}Sign Up{% endblock %}
{% block description %}TaskSphere's sign-up page.{% endblock %}
{% block header %}Sign Up{% endblock %}
{% block content %}
<div class="container appearAnimation text-white mt-3 mb-5 mt-lg-5">
    <form method="post" action="{% url 'authentication:signup' %}" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form-group">
            {{ signUp_form.email.label_tag|linebreaksbr }}
            {% for error in signUp_form.email.errors %}
            <br><span class="form-text text-warning fs-6">{{ error }}</span>
            {% endfor %}
            {{ signUp_form.email }}
            {{ signUp_form.email.help_text|safe }}
        </div>

        <div class="form-group mt-3">
            {{ signUp_form.password1.label_tag }}
            {{ signUp_form.password1 }}
            {{ signUp_form.password1.help_text|safe }}
            
        </div>
        
        <div class="form-group">
            {{ signUp_form.password2.label_tag }}
            {{ signUp_form.password2 }}
            {{ signUp_form.password2.help_text|safe }}
            {% if signUp_form.password2.errors %}
            <div class="form-text text-warning fs-6">
                {{ signUp_form.password2.errors }}
            </div>
            {% endif %}
        </div>

        <div class="row mt-3">
            <div class="col-md-6">
                <div class="form-group">
                    {{ signUp_form.firstname.label_tag }}
                    {% for error in signUp_form.firstname.errors %}
                    <br><span class="form-text text-warning fs-6">{{ error }}</span>
                    {% endfor %}
                    {{ signUp_form.firstname }}
                    {{ signUp_form.firstname.errors }}
                </div>
            </div>
            <div class="col-md-6 mt-3 mt-md-0">
                <div class="form-group">
                    {{ signUp_form.lastname.label_tag }}
                    {% for error in signUp_form.lastname.errors %}
                    <br><span class="form-text text-warning fs-6">{{ error }}</span>
                    {% endfor %}
                    {{ signUp_form.lastname }}
                </div>
            </div>
        </div>

        <div class="form-group mt-3">
            {{ signUp_form.biography.label_tag }}
            {% for error in signUp_form.biography.errors %}
            <br><span class="form-text text-warning fs-6">{{ error }}</span>
            {% endfor %}
            {{ signUp_form.biography }}
            {{ signUp_form.biography.errors }}
        </div>

        <div class="form-group mt-3">
            {{ signUp_form.profile_picture.label_tag }}
            {{ signUp_form.profile_picture }}
            {% for error in signUp_form.profile_picture.errors %}
            <br><span class="form-text text-warning fs-6">{{ error }}</span>
            {% endfor %}
            {{ signUp_form.profile_picture.help_text|safe }}
            
        </div>

        <div class="d-flex justify-content-center"><button type="submit" class="btn border border-white btn-success btn-lg mt-3">Submit</button></div>
    </form>
</div>
<div class="container appearAnimation d-flex align-items-center justify-content-start mb-5 mt-4 mt-md-5">
    <img src="{% static 'icons/arrow-left.svg' %}" alt="Arrow-left">
    <a class="text-white ms-1" href="{% url 'authentication:signin' %}">I already have an account</a>
</div>
{% endblock %}