TaskSphere/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('authentication/', include(('authentication.urls', 'authentication'), namespace='authentication')),
    path('home/', include(('home.urls', 'home'), namespace='home')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/urls.py
from django.urls import path
from authentication import views

urlpatterns = [
    path('', views.main, name='main'),
    path('signin/', views.SignIn, name='signin'),
    path('signup/', views.SignUp, name='signup'),
    path('choosegroupaction', views.ChooseGroupAction, name='choosegroupaction'),
    path('joingroup/', views.JoinGroup, name='joingroup'),
    path('creategroup/', views.CreateGroup, name='creategroup'),
    path('leavegroup/', views.LeaveGroup, name='leavegroup'),
    path('deleteacc/', views.DeleteAccount, name='deleteaccount'),
    path('signout/', views.SignOut, name='signout'),
]

home/urls.py
from django.urls import path
from home import views

urlpatterns = [
    path('', views.main, name='main'),
    path('employees', views.employees_page, name='employees_page')
]

home/models.py
# models.py
from django.db import models
from django.contrib.auth.hashers import make_password, check_password
import uuid
from datetime import datetime
from django.core.validators import MaxValueValidator

class Group(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    group_name = models.CharField(max_length=30)
    givenID = models.CharField(max_length=40, unique=True)  # ID that can be changed
    group_password = models.CharField(max_length=30)
    group_biography = models.TextField(null=True, blank=True)
    created_on = models.DateTimeField(default=datetime.now().strftime('%Y-%m-%d %H:%M:%S'), editable=False)

    def set_password(self, raw_password):
        self.password = make_password(raw_password)  # Hashes and sets the password for the group

    def check_password(self, raw_password):
        return check_password(raw_password, self.password)  # Checks the input of a user

    def __str__(self):
        return f"{self.group_name} || {self.givenID}"
    
    
class Table(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    group = models.OneToOneField(Group, null=True, on_delete=models.CASCADE, editable=False) # Connect to Group
    
    def __str__(self):
        return str(self.id)
        

    
class Table_task(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    task_name = models.CharField(max_length=30, unique=True)
    task_description = models.TextField(max_length=250, blank=True, null=True)
    current_column = models.CharField(max_length=15, blank=False, null=False, choices=[('ToDo', 'ToDo'), ('In progress', 'In progress'), ('Done', 'Done')])
    current_worker = models.CharField(max_length=30) 
    deadLine = models.DateTimeField()
    created_on = models.DateTimeField(default=datetime.now().strftime('%Y-%m-%d %H:%M:%S'), editable=False)
    table = models.ForeignKey(Table, related_name='tasks', on_delete=models.CASCADE, null=False, blank=False, editable=False)  # Connection with table

    def __str__(self):
        return f"Name: {self.task_name} || ID: {self.id} || Created on: {self.created_on} || Table: {self.table}"



home/forms.py
from django import forms
from home.models import Table_task
from authentication.models import User

class CreateTaskForm(forms.ModelForm):
    task_name = forms.CharField(
        label="Taskname", 
        max_length=30, 
        required=True, 
        widget=forms.TextInput(attrs={
            'class': 'form-control', 
            'placeholder': 'Title of the task',
        }),
    )
    task_description = forms.CharField(
        label="Task description",
        max_length=250,
        required=False, 
        widget=forms.Textarea(attrs={
            'class': 'form-control', 
            'placeholder': 'Description of the task', 
            'rows': '4',
        }),
    )
    current_column = forms.ChoiceField(
        choices=[('ToDo', 'ToDo'), ('In progress', 'In progress'), ('Done', 'Done')],
        widget=forms.Select(attrs={
            'class': 'form-select bg-secondary text-white'
        }),
    )
    current_worker = forms.ChoiceField(
        choices=[],  # Wird dynamisch im __init__ gesetzt
        widget=forms.Select(attrs={
            'class': 'form-select bg-secondary text-white'
        }),
        required=True,
        label="Current worker"
    )
    deadLine = forms.DateTimeField(
        label="Deadline",
        required=True,
        widget=forms.DateTimeInput(
            attrs={
                'type': 'datetime-local',
                'class': 'form-control bg-secondary text-white'
            }
        )
    )

    class Meta:
        model = Table_task
        fields = '__all__'

    def __init__(self, *args, group=None, **kwargs):
        super().__init__(*args, **kwargs)
        if group:
            users = group.users.all()
            self.fields['current_worker'].choices = [
                (f"{user.firstname} {user.lastname}") for user in users
            ]

home/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import CreateTaskForm


# Create your views here.
def main(request):
    if not request.user.is_authenticated:
        messages.error(request, "To have access to this page you need to sign in.")
        return redirect('authentication:signin')
    elif request.user.group is None:
        messages.error(request, "To have access to this page you need to be part of a group.")
        return redirect('authentication:choosegroupaction')
    else:
        # Assuming the user has a group and the group has a table

        task_filter = {
            'ToDo': [],
            'In_progress': [],
            'Done': []
        }

        for task in request.user.group.table.tasks.all():
            if task.current_column == 'ToDo':
                task_filter['ToDo'].append(task)
            elif task.current_column == 'In progress':
                task_filter['In_progress'].append(task)
            else: 
                task_filter['Done'].append(task)

        createTask_form = CreateTaskForm(request.POST or None)
            
        return render(request, 'home/main.html', {"task_filter":task_filter, "createTask_form": createTask_form})
    
def employees_page(request):
    if not request.user.is_authenticated:
        messages.error(request, "To have access to this page you need to sign in.")
        return redirect('authentication:signin')
    elif request.user.group is None:
        messages.error(request, "To have access to this page you need to be part of a group.")
        return redirect('authentication:choosegroupaction')
    else:
        # Assuming the user has a group and the group has a table
        employees = request.user.group.users
        return render(request, 'home/employees.html', {'employees': employees})

home/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}Base{% endblock %}</title>
        <meta name="description" content="{% block description %}Base file for the authentication pages.{% endblock %}">
        <meta name="theme-color" content="#121212">
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" type="image/x-icon" href="/static/img/favicon.ico">
        {% load static %}
        <link rel="stylesheet" href="{% static 'bootstrap/bootstrap-5.3.7-dist/css/bootstrap.min.css' %}">
        <script src="{% static 'bootstrap/bootstrap-5.3.7-dist/js/bootstrap.bundle.min.js' %}"></script>


        <style>
            @font-face {
                font-family: 'Roboto';
                src: url('/static/font-families/Roboto/Roboto-Regular.ttf') format('truetype');
            }

            @font-face {
                font-family: 'Roboto-Bold';
                src: url('/static/font-families/Roboto/Roboto-Bold.ttf') format('truetype');
            }

            @keyframes appear {
                0% {
                    transform: translateY(100%); 
                    opacity: 0; 
                }
                100% {
                    transform: translateY(0); 
                    opacity: 1;
                }
    
            }

            .appearAnimation {
                animation: appear 0.7s ease-out 1;
            }

            @keyframes appearWithoutMoving {
                0% {
                    opacity: 0; 
                }
                100% {
                    opacity: 1;
                }
    
            }

            .appearWithoutMovingAnimation {
                animation: appearWithoutMoving 1s ease-out 1;
            }

            body {
                font-family: 'Roboto';
                margin: 0px;
                transition: 1s;
                background-color: #222831;
            }

            .alert {
                opacity: 1;
                transition: transform 0.6s ease-out;
            }
    
            .alert.error {background-color: #f44336;}
            .alert.success {background-color: #4CAF50;} /* Green */
            .alert.info {background-color: #2196F3;} /* Blue */
            .alert.warning {background-color: #ff9800;} /* Orange */
    
            .closebtn {
                line-height: 20px;
                cursor: pointer;
                transition: 0.3s;
            }
    
            .closebtn:hover {
                color: black !important;
            }
            
            .settings_btn {
                transition: transform 1s ease-in-out;
            }

            .settings_btn:hover {
                transform: rotate(180deg);
            }
        </style>
    </head>
    <body>

        <nav class="navbar bg-info text-white bg-opacity-75 fixed-top" data-bs-theme="dark">
            <div class="container-fluid px-2 px-sm-3 px-md-4">
                <div>
                    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class="navbar-brand ms-md-4 ms-2" href="{% url 'home:main' %}">
                        {% if user.group.group_name|length > 10 %}
                            {{ user.group.group_name|slice:":10" }}...
                        {% else %}
                            {{ user.group.group_name }}
                        {% endif %}
                    </a>
                </div>
                <div class="fs-5 me-3">
                    <span class="d-sm-inline d-none">{{user.firstname}}</span>
                    <img src="{{user.profile_picture.url}}" alt="Profile Picture" class="rounded-circle ms-2" style="width: 40px; height: 40px;">
                    <div class="btn-group ms-3">
                        <button type="button" class="btn p-0 border-0 bg-transparent dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" style="width: 30px; height: 30px;">
                            <img class="settings_btn" style="width: 30px; height: 30px;" src="{% static 'icons/gear.svg' %}" alt="Settings">
                        </button>
                        <ul class="dropdown-menu dropdown-menu-end">
                            <li><a class="dropdown-item" href="#">My profile</a></li>
                            <li><a class="dropdown-item" href="#">Group profile</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'authentication:signout' %}">Sign out</a></li>
                        </ul>
                    </div>
                </div>
                <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
                    <div class="offcanvas-header">
                    <h5 class="offcanvas-title" id="offcanvasNavbarLabel">{{user.firstname}} {{user.lastname}} - {{ user.group.group_name|slice:":10" }}</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                </div>
                <div class="offcanvas-body">
                    <div class="d-flex flex-column justify-content-between h-100">
                        <div>
                            <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                                <li class="nav-item">
                                    <a class="nav-link {% if request.resolver_match.url_name == 'main' %}active{% endif %}" href="{% url 'home:main' %}">Home</a>
                                    <a class="nav-link {% if request.resolver_match.url_name == 'employees_page' %}active{% endif %}" href="{% url 'home:employees_page' %}">Employees</a>
                                    <a class="nav-link {% if request.resolver_match.url_name == 'messanger' %}active{% endif %}" href="#">Messenger</a>
                                    <a class="nav-link {% if request.resolver_match.url_name == 'notifications' %}active{% endif %}" href="#">Notifications</a>
                                    <a class="nav-link {% if request.resolver_match.url_name == 'general_settings' %}active{% endif %}" href="#">General settings</a>
                                </li>
                            </ul>
                        </div>

                        <div>
                            <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                                <li class="nav-item d-flex flex-row justify-content-between">
                                    <a class="nav-link text-light text-decoration-underline fs-6" href="#">Data usage</a>
                                    <a class="nav-link text-light text-decoration-underline fs-6" href="#">Terms of service</a>
                                    <a class="nav-link text-light text-decoration-underline fs-6" href="#">Copyright page</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </nav>

        
        <div style="margin-top: 80px;">
            {% if messages %}
            <div id="messages" class="messages">
                {% for message in messages %}
                    <div class="alert {{ message.tags }} alert-dismissible fade show text-light d-flex align-items-center justify-content-center fs-6 border-1 border-white" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="" aria-label="" onclick="closeAlert(this)"></button>
                    </div>
                {% endfor %}
            </div>
            {% endif %}
            {% block content %}{% endblock %}
        </div>


        <script async defer>
            function closeAlert(element) {
                let alert = element.parentElement;
                let container = document.getElementById('messages')
                alert.style.transform = 'translateY(-100%)';
                setTimeout(function() {
                    alert.style.display = 'none';
                    container.style.display = 'none'
                }, 600); // Waits till transition is over
            }
        </script>
    </body>
</html>

home/templates/home/employees.html
{% extends 'home/base.html' %}
{% load static %}
{% block title %}Employees in your group{% endblock %}
{% block description %}All employees in your group{% endblock %}

{% block content %}
<h4 class="text-light ms-4">A list of all employees in your group.</h4>
<div class="px-5 mb-3">
  <input type="text" onkeyup="searchEmployee()" id="employeeSearch" class="form-control" placeholder="Search employees...">
</div>

<ul id="employees_list" class="list-group px-5">
    <li class="list-group-item list-group-item-dark" aria-current="true">
        <img src="{{user.profile_picture.url}}" alt="Profile Picture" class="rounded-circle ms-2" style="width: 40px; height: 40px;">
        <span class="ms-2">{{request.user.firstname}} {{request.user.lastname}}</span>
    </li>
    {% for user in request.user.group.users.all %}
    {% if not user == request.user %}
    <li class="list-group-item d-flex justify-content-between align-items-center" aria-current="true">
        <div>
            <img src="{{user.profile_picture.url}}" alt="Profile Picture" class="rounded-circle ms-2" style="width: 40px; height: 40px;">
            <span class="ms-2">{{user.firstname}} {{user.lastname}}</span>
        </div>
        <div>
            <button type="button" title="Message the person" class="btn btn-outline-secondary border-white p-0 border-2 rounded-circle me-3" style="width: 40px; height: 40px;">
                <a href=""><img src="{% static 'icons/chat_symbol.svg' %}" alt="Messenger"></a>
            </button>
            <button type="button" title="Information about the person" class="btn btn-outline-secondary border-white p-0 border-2 rounded-circle" style="width: 40px; height: 40px;">
                <a href=""><img src="{% static 'icons/person.svg' %}" alt="Information"></a>
            </button>
        </div>
    </li>
    {% endif %}
    {% endfor %}
</ul>

<script>
    function searchEmployee() {
        // Declare variables
        var input, filter, ul, li, a, i, txtValue;
        input = document.getElementById('employeeSearch');
        filter = input.value.toUpperCase();
        ul = document.getElementById("employees_list");
        li = ul.getElementsByTagName('li');

        // Loop through all list items, and hide those who don't match the search query
        for (i = 0; i < li.length; i++) {
            span = li[i].getElementsByTagName("span")[0];
            txtValue = span.textContent || span.innerText;
            if (txtValue.toUpperCase().indexOf(filter) > -1) {
            li[i].classList.remove('d-none');
            } else {
            li[i].classList.add('d-none');
            }
        }
    }
</script>
{% endblock %}

home/templates/home/main.html
{% extends 'home/base.html' %}
{% block title %}Home{% endblock %}
{% block description %}TaskSphere's home page.{% endblock %}

{% block content %}
<div class="d-flex g-0 row w-100 text-light">
    
    <div class="col-lg-4 col-12 h-75 d-flex flex-column border border-2 border-end-0 rounded-2 rounded-top-0">
        <div class="fs-4 text-decoration-underline d-flex justify-content-center align-items-center border-bottom bg-danger">
            ToDo
        </div>
        {% for task in task_filter.ToDo %}
        <div class="card text-bg-secondary my-3 mx-5 text-center">
            <div class="card-header bg-dark fs-5 fw-bold">
                {{task.task_name}}
            </div>
            <div class="card-body">
                <p class="card-text">{{task.task_description}}</p>
                {% if task.current_worker %}
                <p class="card-text">Current worker: {{task.current_worker}}</p>
                {% else %}
                <p class="card-text">Current worker: <span class="fst-italic">No current worker...</span></p>
                {% endif %}
                <a href="#" class="btn btn-primary">Edit</a>
            </div>
            <div class="card-footer text-warning">
                Deadline: {{task.deadLine}}
            </div>
        </div>
        {% empty %}
        <div class="text-white-50 d-flex justify-content-center fs-5 fst-italic my-3">No tasks...</div>
        {% endfor %}
    </div>
    <div class="col-lg-4 col-12 h-75 d-flex flex-column border border-2 border-end-0 rounded-2 rounded-top-0">
        <div class="fs-4 text-decoration-underline d-flex justify-content-center align-items-center border-bottom bg-warning">
            In progress
        </div>
        {% for task in task_filter.In_progress %}
        <div class="card text-bg-secondary my-3 mx-5 text-center">
            <div class="card-header bg-dark fs-5 fw-bold">
                {{task.task_name}}
            </div>
            <div class="card-body">
                <p class="card-text">{{task.task_description}}</p>
                {% if task.current_worker %}
                <p class="card-text">Current worker: {{task.current_worker}}</p>
                {% else %}
                <p class="card-text">Current worker: <span class="fst-italic">No current worker...</span></p>
                {% endif %}
                <a href="#" class="btn btn-primary">Edit</a>
            </div>
            <div class="card-footer text-warning">
                Deadline: {{task.deadLine}}
            </div>
        </div>
        {% empty %}
        <div class="text-white-50 d-flex justify-content-center fs-5 fst-italic my-3">No tasks...</div>
        {% endfor %}
    </div>
    <div class="col-lg-4 col-12 h-75 d-flex flex-column border border-2 rounded-2 rounded-top-0">
        <div class="fs-4 text-decoration-underline d-flex justify-content-center align-items-center border-bottom bg-success">
            Done
        </div>
        {% for task in task_filter.Done %}
        <div class="card text-bg-secondary my-3 mx-5 text-center">
            <div class="card-header bg-dark fs-5 fw-bold">
                {{task.task_name}}
            </div>
            <div class="card-body">
                <p class="card-text">{{task.task_description}}</p>
                {% if task.current_worker %}
                <p class="card-text">Current worker: {{task.current_worker}}</p>
                {% else %}
                <p class="card-text">Current worker: <span class="fst-italic">No current worker...</span></p>
                {% endif %}
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#{{task.id}}">Edit</button>
            </div>
            <div class="card-footer text-warning">
                Deadline: {{task.deadLine}}
            </div>
        </div>

        <div class="modal fade" id="{{task.id}}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="{{task.task_name}}" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="staticBackdropLabel">{{task.task_name}}</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form method="post" id="edit-task-{{task.id}}">
                            {% csrf_token %}
                            <div class="mb-3">
                                {{ createTask_form.task_name }}
                            </div>
                            <div class="mb-3">
                                {{ createTask_form.task_description }}
                            </div>
                            <div class="mb-3">
                                {{ createTask_form.current_column }}
                            </div>
                            <div class="mb-3">
                                {{ createTask_form.current_worker }}
                            </div>
                            <div class="mb-3">
                                {{ createTask_form.deadLine }}
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Discard changes</button>
                        <button onclick="deleteInputValue(this)" form="edit-task-{{task.id}}" type="submit" class="btn btn-success">Save changes</button>
                    </div>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="text-white-50 d-flex justify-content-center fs-5 fst-italic my-3">No tasks...</div>
        {% endfor %}
    </div>
</div>

<script>
    function deleteInputValue(element) {
        let formId = element.getAttribute('form');
        let form = document.getElementById(formId);
        if (!form) return;
        let fields = form.querySelectorAll('input, select, textarea');
        fields.forEach(function(field) {
            // CSRF-Token nicht löschen
            if (field.type === 'hidden' && field.name === 'csrfmiddlewaretoken') return;
            if (field.type === 'checkbox' || field.type === 'radio') {
                field.checked = false;
            } else if (field.tagName.toLowerCase() === 'select') {
                field.selectedIndex = 0;
            } else {
                field.value = '';
            }
        });
    }
</script>
{% endblock %}